name = Home
description = Ethiodiaspoera Home pages layout is here.

template = home-layout

; ========================================
; Regions
; ========================================
regions[branding] = Branding
regions[header] = Header
regions[navigation] = Navigation
regions[highlighted] = Highlighted
regions[help] = Help
regions[main_video] = Main Video
regions[main_audio] = Main Audio
regions[sectional_one] = Sectional One
regions[sectional_two] = Sectional Two
regions[sectional_three] = Sectional Three
regions[content] = Content
regions[sidebar_second] = Second Sidebar
regions[footer_gallary] = Footer Gallary
regions[footer] = Footer

;styles
stylesheets[all][] = css/layouts/home/home.layout.css
stylesheets[all][] = css/layouts/home/home.layout.no-qurery.css

