name = Internal
description = Ethiodiaspoera Internal pages layout is here.

template = internal-layout

; ========================================
; Regions
; ========================================
regions[branding] = Branding
regions[header] = Header
regions[navigation] = Navigation
regions[highlighted] = Highlighted
regions[help] = Help
regions[content] = Content
regions[sidebar_second] = Second Sidebar
regions[footer_gallary] = Footer Gallary
regions[footer] = Footer

;styles
stylesheets[all][] = css/layouts/internal/internal.layout.css
stylesheets[all][] = css/layouts/internal/internal.layout.no-qurery.css
