name = Interior
description = This layout used for the interior pages.

template = interior-layout

; ========================================
; Regions
; ========================================
regions[branding] = Branding
regions[header] = Header
regions[navigation] = Navigation
regions[highlighted] = Highlighted
regions[help] = Help
regions[content] = Content
regions[sidebar_second] = Second Sidebar
regions[footer_gallary] = Footer Gallary
regions[footer] = Footer

;styles
stylesheets[all][] = css/layouts/interior/interior.layout.css
stylesheets[all][] = css/layouts/interior/interior.layout.no-qurery.css

